config/routes.rb
Rails.application.routes.draw do
  resources :technicalsupports do
    resources :tecnichsales 
  end
  resources :faultreqs
  resources :orders do
    resources :reqitems
  end
  resources :baskets do
    resources :salesproducts
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :customerbalances
  
  resources :products
  resources :brands
  get 'customer/index'
  get 'customer/new'
  get 'customer/show'
  get 'customer/edit'
  #sessions
  resource :session ,only: [:new, :create, :destroy]
  get '/oturum_ac', to: 'sessions#new', as: :login
  delete '/oturumu_kapat', to: 'sessions#destroy', as: :logout

  resources :users
  get '/kaydol', to: 'users#new',  as: :register
  get '/users/new', to: redirect('/kaydol')
  get '/:id', to: 'users#show', as: :profile
  get '/:id/edit', to: 'users#edit', as: :edit_profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sessions#new"
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
belongs_to :user
has_many :salesproducts
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
	validates :name, presence: true
	validates :name, :uniqueness => true
	before_save :uppercase_name
	def uppercase_name
		self.name.upcase!
	end
end

app/models/customerbalance.rb
class Customerbalance < ApplicationRecord
	belongs_to :user
end

app/models/faultreq.rb
class Faultreq < ApplicationRecord
belongs_to :user
has_one_attached :image
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :recipient, class_name: "User"
	belongs_to :actor, class_name: "User"
	belongs_to :notifiable, polymorphic: true

	scope :unread, ->{ where(:read_at=>nil) }
	scope :recent, ->{ order(created_at: :desc).limit(5) }
end

app/models/order.rb
class Order < ApplicationRecord
has_many :reqitems
belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :salesproducts
	has_many :reqitems
	has_many :tecnichsales
	belongs_to :brand
	validates :name, presence: true
	validates :amount, presence: true
	validates :unit_price, presence: true

end

app/models/reqitem.rb
class Reqitem < ApplicationRecord
	belongs_to :product
	belongs_to :order
end

app/models/salesproduct.rb
class Salesproduct < ApplicationRecord
belongs_to :product
belongs_to :user
belongs_to :basket
end

app/models/technicalsupport.rb
class Technicalsupport < ApplicationRecord
belongs_to :user
has_many :tecnichsales
end

app/models/tecnichsale.rb
class Tecnichsale < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :notifications, foreign_key: :recipient_id
	
	has_many :customerbalances
	has_many :orders
	has_many :salesproducts
	has_many :tecnichsales
	has_many :faultreqs
	has_many :baskets
	has_many :technicalsupports
	validates :username,   presence:   true,
	exclusion: {in: ['oturum_ac']},
	uniqueness: { case_sensitive: false },
	length:     { in: 4..12 },
	format:     { with: /\A[a-zA-Z][a-zA-Z0-9_-]*\Z/ },
	exclusion:  { in: ['oturum_ac'] }
	validates :first_name, presence:   true
	validates :last_name,  presence:   true
	validates :company_name, presence:   true
	validates :email,      presence:   true,
	uniqueness: { case_sensitive: false },
	email:      true

	def to_param
		username
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#	before_action :validate_user!,only: [:show,:edit,:update,:destroy]
before_action :select_user, only: [:show, :edit, :update, :destroy]
before_action only: [:edit, :update, :destroy] do
	validate_permission! select_user
end
def index
	@users=User.all
end
def new
	@user=User.new
end
def create
	@user=User.new(user_params)
	@user.admin=false
	if @user.save
		login(@user)
		redirect_to @user, notice: 'Aramıza hoşgeldin.'
	else
		render :new
	end

end

def show

	
	if Customerbalance.find_by_user_id(@user.id)==nil
		@total_balance=0.0
	else
		@total_balance=Customerbalance.find_by_user_id(@user.id).total_balance
	end
	@user_orders=Order.where(user_id: current_user.id)
	@orders = @user_orders.all.order('created_at DESC')
end
def edit
end
def create_order
	@order=Order.new
	@order.user=current_user
	@order.save
	redirect_to @order	
end

def update
	update_params = user_params
	if update_params.has_key?(:password)
		update_params.delete([:password, :password_confirmation])
	end

	if @user.update(update_params)
		redirect_to @user, notice: 'Profil bilgileriniz güncellendi.'
	else
		render :edit, layout: "profile"
	end
end
def destroy
	logout
	@user.destroy
	redirect_to root_url
end
private
def user_params
	params.require(:user).permit!
end
def select_user
	@user = User.find_by_username(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/faultreqs_helper.rb
module FaultreqsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reqitems_helper.rb
module ReqitemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <div class="wrapper ">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3"></div>

          <div class="col-md-6">
            <div class="card">
              <div class="card-header card-header-primary">
                <img class="img pull-right" src="/assets/kep.png" style="width: 90px; height: 90px; padding-top: 20px;" />
                <h4 class="card-title" style="padding-top: 20px;">Kayıt</h4>
                <p class="card-category">Otomasyon Kayıt</p>
              </div>
              <div class="card-body">
               <%=form_for @user, data: {abide: ''} do |form|%>
               <%if @user.errors.any?%>
               <div class="row panel callout radius">
                 <p>Aşağıdaki hataları düzeltip, tekrar deneyiniz.</p>
                 <ul class="square">
                   <%@user.errors.full_messages.each do |message|%>
                   <li><%=message%></li>
                   <%end%>
                 </ul>
               </div>
               <%end%>
               <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Adınız</label>
                    <%=form.text_field :first_name, class: "form-control"%>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Soyadınız</label>
                    <%=form.text_field :last_name, class: "form-control"%>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Kullanıcı Adı</label>
                    <%=form.text_field :username, class: "form-control"%>
                  </div>
                </div>
              </div>
                <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Şirket Adı</label>
                    <%=form.text_field :company_name, class: "form-control"%>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">E-Posta</label>
                    <%=form.email_field :email, class: "form-control"%>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Şifre</label>
                    <%=form.password_field :password, class: "form-control"%>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Şifre tekrar</label>
                    <%=form.password_field :password_confirmation,class: "form-control"%>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary btn-block ">Kayıt Ol</button>
              <%end%>
            </div>
          </div>
        </div>
        <div class="col-md-3"></div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="wrapper ">
	<%= render 'shared/sidebar'%>
	<div class="main-panel">
		<%= render 'shared/navbar'%>
		<div class="content">

			<div class="container-fluid">

				<br>
				<div class="row">
					<div class="col-md-3"><!--left col-->

						<div class="text-center">
							<img src="/assets/kep.png" style="width: 250px; height: 200px;" class="avatar img-circle img-thumbnail" alt="avatar">
						</div>
						<hr> 
						<h3 class="text-center"><%="#{@user.first_name} #{@user.last_name}"%></h3>
						<hr>

						<%=link_to "Hesabı Düzenle", edit_user_path(@user), class: "btn btn-primary btn-round btn-block"%>

						<%= button_to "Hesabı sil", @user, method: :delete, data:{confirm: 'Hesabı silmek istediğinize emin misiniz?'}, class: "btn btn-primary btn-round btn-block" %></p>
						<br>
					</div><!--/col-3-->


					<div class="col-md-9">
						<div class="card">
							<div class="card-header card-header-primary">
								<img class="img pull-right" src="/assets/kep.png" style="width: 90px; height: 90px; padding-top: 20px;" />
								<h4 class="card-title" style="padding-top: 20px;">Kayıt</h4>
								<p class="card-category">Otomasyon Kayıt</p>
							</div>
							<div class="card-body">
								<%=form_for @user, data: {abide: ''} do |form|%>
								<%if @user.errors.any?%>
								<div class="row panel callout radius">
									<p>Aşağıdaki hataları düzeltip, tekrar deneyiniz.</p>
									<ul class="square">
										<%@user.errors.full_messages.each do |message|%>
										<li><%=message%></li>
										<%end%>
									</ul>
								</div>
								<%end%>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label class="bmd-label-floating">Şirket Adı</label>
											<%=form.text_field :company_name, class: "form-control"%>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label class="bmd-label-floating">Adınız</label>
											<%=form.text_field :first_name, class: "form-control"%>
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label class="bmd-label-floating">Soyadınız</label>
											<%=form.text_field :last_name, class: "form-control"%>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label class="bmd-label-floating">Kullanıcı Adı</label>
											<%=form.text_field :username, class: "form-control"%>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label class="bmd-label-floating">E-Posta</label>
											<%=form.email_field :email, class: "form-control"%>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label class="bmd-label-floating">Şifre</label>
											<%=form.password_field :password, class: "form-control"%>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label class="bmd-label-floating">Şifre tekrar</label>
											<%=form.password_field :password_confirmation,class: "form-control"%>
										</div>
									</div>
								</div>
								<div class="row">

									<div class="col-md-6">
										<%= link_to 'Geri', :back, class: "btn btn-primary btn-block" %>
									</div>
									
									<div class="col-md-6"><button type="submit" class="btn btn-primary btn-block ">Kayıt Ol</button>
									</div>

								</div>
								<%end%>
							</div>
						</div>
					</div>

				</div>
			</div>

		</div>
		<%= render 'shared/footer'%>
	</div>
</div>

app/views/users/index.html.erb
 <div class="wrapper ">
  <%= render 'shared/sidebar'%>
  <div class="main-panel">
    <%= render 'shared/navbar'%>
    <div class="content">

      <div class="container-fluid">

        <br>
        <div class="row">
          <div class="col-md-3"><!--left col-->

            <div class="text-center">
              <img src="/assets/kep.png" style="width: 250px; height: 200px;" class="avatar img-circle img-thumbnail" alt="avatar">
            </div>
            <hr> 
            <h3 class="text-center"><%=current_user.first_name%>  <%=current_user.last_name%></h3>
            <hr>          
            
          </div><!--/col-3-->
          <div class="col-md-9">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">

                 <div class="row">
                  <div class="col-md-6">
                    <h4 class="card-title ">Kullanıcılar</h4>
                    <p class="card-category">Kullanıcılar Listesi</p>
                  </div>
                  <div class="col-md-6">

                    <form class="navbar-form">
                      <div class="input-group no-border">
                        <input type="text" id="search" onkeyup="myFunction()" value="" class="form-control" placeholder="Kullanıcı İsiminde Arayınız." style="color: white;">
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                          <i class="material-icons">search</i>
                          <div class="ripple-container"></div>
                        </button>
                      </div>
                    </form>  

                  </div>
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive">

                 <table class="table" id="myTable">
                  <thead>
                    <tr>
                     <th>Adı Soyadı</th>
                     <th>Şirket Adı</th>
                     <th>Seçenekler</th>
                     
                   </tr>
                 </thead>
                 <tbody class="items">
                  <% @users.each do |user| %>
                  <tr>
                    <td><%=user.first_name%>  <%=user.last_name%></td>
                    <td><%=user.company_name%></td>
                    <td><%= link_to 'Göster',profile_path(user)%><%= link_to 'Sil' ,user, method: :delete, data: { confirm: 'Are you sure?' }%></td>              
                  </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<%= render 'shared/footer'%>
</div>
</div>

<script>  
  $(document).ready(function(){  
   $('#search').keyup(function(){  
    search_table($(this).val());  
  });  
   function search_table(value){  
    $('#myTable tr').each(function(){  
     var found = 'false';  
     $(this).each(function(){  
      if($(this).text().toUpperCase().indexOf(value.toUpperCase()) >= 0)  
      {  
       found = 'true';  
     }  
   });  
     if(found == 'true')  
     {  
      $(this).show();  
    }  
    else  
    {  
      $(this).hide();  
    }  
  });  
  }  
});  
</script>  

app/views/users/new.html.erb
<%=render 'form'%>

app/views/users/show.html.erb
 <div class="wrapper ">
 	<%= render 'shared/sidebar'%>
 	<div class="main-panel">
 		<%= render 'shared/navbar'%>
 		<div class="content">
 			<div class="container-fluid">
 				<div class="row">
 					<div class="col-lg-4 col-md-6 col-sm-6">
 						<div class="card card-stats">
 							<div class="card-header card-header-success card-header-icon">
 								<div class="card-icon">
 									<i class="fa fa-money"></i>
 								</div>
 								<p class="card-category">Toplam Borç</p>
 								<h5 class="card-title"><%=@total_balance%> TL</h5>
 							</div>
 							<div class="card-footer">
 								<div class="stats">
 									<i class="material-icons">date_range</i> Son 24 Saat
 								</div>
 							</div>
 						</div>
 					</div>
 					<div class="col-lg-4 col-md-6 col-sm-6">
 						<div class="card card-stats">
 							<div class="card-header card-header-warning card-header-icon">
 								<div class="card-icon">
 									<i class="fa fa-shopping-basket"></i>
 								</div>
 								<p class="card-category">Toplam Alışveriş Sayısı</p>
 								<h5 class="card-title"><%=Basket.where(:user_id=>@user.id).count%></h5>
 							</div>
 							<div class="card-footer">
 								<div class="stats">
 									<i class="material-icons">date_range</i> Last 24 Hours
 								</div>
 							</div>
 						</div>
 					</div>
 					<div class="col-lg-4 col-md-6 col-sm-6">
 						<div class="card card-stats">
 							<div class="card-header card-header-danger card-header-icon">
 								<div class="card-icon">
 									<i class="fa fa-tools"></i>
 								</div>
 								<p class="card-category">Toplam Bakım Onarım Sayısı</p>
 								<h5 class="card-title"><%=Technicalsupport.where(:user_id=>@user.id).count%></h5>
 							</div>
 							<div class="card-footer">
 								<div class="stats">
 									<i class="material-icons">date_range</i> Last 24 Hours
 								</div>
 							</div>
 						</div>
 					</div>
 				</div>
 				<hr>
 				<br>
 				<div class="row">
 					<div class="col-md-3"><!--left col-->

 						<div class="text-center">
 							<img src="/assets/kep.png" style="width: 250px; height: 200px;" class="avatar img-circle img-thumbnail" alt="avatar">
 						</div>
 						<hr> 
 						<h3 class="text-center"><%=@user.first_name%>  <%=@user.last_name%></h3>
 						<hr>
 						
 						<%=link_to 'New Technicalsupport Form', new_technicalsupport_path(:u_id=>@user.id),class: "btn btn-primary btn-round btn-block"%>

 						<%= form_with(model: Order.new, local: true) do |form| %>

 						<div class="field">
 							<%=form.hidden_field :user_id, value:@user.id%>
 							<%= form.hidden_field :req_key %>
 						</div>

 						<div class="actions">
 							<%= form.submit 'Sipariş Oluştur',class: "btn btn-primary btn-round btn-block" %>
 						</div>
 						<% end %>	
 						<%= form_with(model: Basket.new, local: true) do |form| %>

 						<div class="field">
 							<%=form.hidden_field :user_id, value:@user.id%>

 							<%= form.hidden_field :key %>
 						</div>

 						<div class="actions">
 							<%= form.submit 'Satış Oluştur',class: "btn btn-primary btn-round btn-block" %>
 						</div>
 						<% end %>
 						<hr>					
 						<% if current_user==@user%>
 						<%=link_to "Hesabı Düzenle", edit_user_path(@user), class: "btn btn-primary btn-round btn-block"%>

 						<%= button_to "Hesabı sil", @user, method: :delete, data:{confirm: 'Hesabı silmek istediğinize emin misiniz?'}, class: "btn btn-primary btn-round btn-block" %></p>
 						<%end%>
 						<br>
 					</div><!--/col-3-->
 					<div class="col-md-9">
 						<div class="col-md-12">
 							<div class="row">
 								<div class=" col-md-6 col-sm-6">
 									<div class="card card-stats">
 										<div class="card-header card-header-success card-header-icon">
 											<div class="card-icon">
 												<i class="fa fa-wrench"></i>
 											</div>
 											<p class="card-category"></p>
 											<h5><%=link_to 'Yapılan Tüm Bakımlar',technicalsupports_path(:user_id=>@user.id),class: "card-title"%></h5>
 										</div>
 										<div class="card-footer">
 											<div class="stats">
 												<i class="material-icons">date_range</i> Last 24 Hours
 											</div>
 										</div>
 									</div>
 								</div>
 								<div class=" col-md-6 col-sm-6">
 									<div class="card card-stats">
 										<div class="card-header card-header-success card-header-icon">
 											<div class="card-icon">
 												<i class="fa fa-shopping-basket"></i>
 											</div>
 											<p class="card-category"></p>
 											<h5><%=link_to 'Alınan Malların Sepet Listesi', baskets_path(:user_id=>@user.id), class: "card-title"%></h5>
 										</div>
 										<div class="card-footer">
 											<div class="stats">
 												<i class="material-icons">date_range</i> Last 24 Hours
 											</div>
 										</div>
 									</div>
 								</div>

 							</div>
 						</div>
 					</div>

 				</div>
 			</div>

 		</div>
 		<%= render 'shared/footer'%>
 	</div>
 </div>

 <script>  
 	$(document).ready(function(){  
 		$('#search').keyup(function(){  
 			search_table($(this).val());  
 		});  
 		function search_table(value){  
 			$('#myTable tr').each(function(){  
 				var found = 'false';  
 				$(this).each(function(){  
 					if($(this).text().toUpperCase().indexOf(value.toUpperCase()) >= 0)  
 					{  
 						found = 'true';  
 					}  
 				});  
 				if(found == 'true')  
 				{  
 					$(this).show();  
 				}  
 				else  
 				{  
 					$(this).hide();  
 				}  
 			});  
 		}  
 	});  
 </script>  