config/routes.rb
Rails.application.routes.draw do
  resources :technicalsupports do
    resources :tecnichsales 
  end
  resources :faultreqs
  resources :orders do
    resources :reqitems
  end
  resources :baskets do
    resources :salesproducts
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :customerbalances
  
  resources :products
  resources :brands
  get 'customer/index'
  get 'customer/new'
  get 'customer/show'
  get 'customer/edit'
  #sessions
  resource :session ,only: [:new, :create, :destroy]
  get '/oturum_ac', to: 'sessions#new', as: :login
  delete '/oturumu_kapat', to: 'sessions#destroy', as: :logout

  resources :users
  get '/kaydol', to: 'users#new',  as: :register
  get '/users/new', to: redirect('/kaydol')
  get '/:id', to: 'users#show', as: :profile
  get '/:id/edit', to: 'users#edit', as: :edit_profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sessions#new"
  
  
end

app/models/basket.rb
class Basket < ApplicationRecord
belongs_to :user
has_many :salesproducts
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
	validates :name, presence: true
	validates :name, :uniqueness => true
	before_save :uppercase_name
	def uppercase_name
		self.name.upcase!
	end
end

app/models/customerbalance.rb
class Customerbalance < ApplicationRecord
	belongs_to :user
end

app/models/faultreq.rb
class Faultreq < ApplicationRecord
belongs_to :user
has_one_attached :image
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :recipient, class_name: "User"
	belongs_to :actor, class_name: "User"
	belongs_to :notifiable, polymorphic: true

	scope :unread, ->{ where(:read_at=>nil) }
	scope :recent, ->{ order(created_at: :desc).limit(5) }
end

app/models/order.rb
class Order < ApplicationRecord
has_many :reqitems
belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :salesproducts
	has_many :reqitems
	has_many :tecnichsales
	belongs_to :brand
	validates :name, presence: true
	validates :amount, presence: true
	validates :unit_price, presence: true

end

app/models/reqitem.rb
class Reqitem < ApplicationRecord
	belongs_to :product
	belongs_to :order
end

app/models/salesproduct.rb
class Salesproduct < ApplicationRecord
belongs_to :product
belongs_to :user
belongs_to :basket
end

app/models/technicalsupport.rb
class Technicalsupport < ApplicationRecord
belongs_to :user
has_many :tecnichsales
end

app/models/tecnichsale.rb
class Tecnichsale < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :notifications, foreign_key: :recipient_id
	
	has_many :customerbalances
	has_many :orders
	has_many :salesproducts
	has_many :tecnichsales
	has_many :faultreqs
	has_many :baskets
	has_many :technicalsupports
	validates :username,   presence:   true,
	exclusion: {in: ['oturum_ac']},
	uniqueness: { case_sensitive: false },
	length:     { in: 4..12 },
	format:     { with: /\A[a-zA-Z][a-zA-Z0-9_-]*\Z/ },
	exclusion:  { in: ['oturum_ac'] }
	validates :first_name, presence:   true
	validates :last_name,  presence:   true
	validates :company_name, presence:   true
	validates :email,      presence:   true,
	uniqueness: { case_sensitive: false },
	email:      true

	def to_param
		username
	end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/faultreqs_helper.rb
module FaultreqsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reqitems_helper.rb
module ReqitemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_footer.html.erb
 <footer class="footer">
  <div class="container-fluid">
    <nav class="float-left">
      <ul>
        <li>
          <a href="https://www.creative-tim.com">
            Bera Ar-Ge & Yazılım & Danışmanlık 
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright float-right">
      &copy;
      2018<i class="material-icons">favorite</i>
      <a href="http://berayazilim.net" target="_blank">Bera Ar-Ge & Yazılım & Danışmanlık </a> tarafından hazırlanmıştır.
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand" href="#pablo"></a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
      <span class="sr-only">Toggle navigation</span>
      <span class="navbar-toggler-icon icon-bar"></span>
      <span class="navbar-toggler-icon icon-bar"></span>
      <span class="navbar-toggler-icon icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item dropdown" data-behavior="notifications">
          <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Bildirimler
            <i class="material-icons">notifications</i>
            <span class="notification">5</span>

            <p class="d-lg-none d-md-block">
              Some Actions
            </p>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink" data-behavior="notification-items">
           <!-- <a class="dropdown-item" href="#">Mike John responded to your email</a>
            <a class="dropdown-item" href="#">You have 5 new tasks</a>
            <a class="dropdown-item" href="#">You're now friend with Andrew</a>
            <a class="dropdown-item" href="#">Another Notification</a>
            <a class="dropdown-item" href="#">Another One</a>
            
            <h5 class="text-center"></h5> -->
            
          </div> 
        </li>
        

        <li class="nav-item dropdown">
          <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons">person</i>
            <%=current_user.first_name%> <%=current_user.last_name%> 
            <p class="d-lg-none d-md-block">
              Some Actions
            </p>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <%if signed_in?%>
            <a class="dropdown-item" href="<%=edit_profile_path(current_user)%>">
              <i class="material-icons" style="margin-right: 10px;">settings</i>Hesabı Düzenle
            </a>
            <a class="dropdown-item" href="<%=logout_path%>"  data-method="delete">
              <i class="material-icons" style="margin-right: 10px;">power_settings_new</i>Çıkış
            </a>
            <%end%> 
            
            <h5 class="text-center"></h5>
          </div>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
 <div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/sidebar-2.jpg">

  <div class="logo">
    <a href="#" class="simple-text logo-normal">
      Müşteri Takip Otomasyonu
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="<%=profile_path(current_user)%>">
          <i class="material-icons">person</i>
          <p>Profilime Git</p>
        </a>
      </li>
      <%if current_user.admin?%>
      <li class="nav-item">
        <a class="nav-link" href="<%=new_brand_path%>">
          <i class="material-icons">bookmarks</i>
          <p>Marka Tanımla</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=new_product_path%>">
          <i class="material-icons">bookmarks</i>
          <p>Ürün Ekle</p>
        </a>
      </li>
      
      <%end%>
      <li class="nav-item">
        <a class="nav-link" href="<%=new_faultreq_path%>">
          <i class="fas fa-tools"></i>
          <p>Arıza Bildir</p>
        </a>
      </li> 
      <li class="nav-item">
        <a class="nav-link" href="<%=faultreqs_path%>">
          <i class="fas fa-tools"></i>
          <p>Arıza Bildirim Listesi</p>
        </a>
      </li>          
      <li class="nav-item">
        <a class="nav-link" href="<%=baskets_path(:user_id=>nil)%>">
          <i class="material-icons">shopping_basket</i>
          <p>Satış Sepet Listeleri</p>
        </a>
      </li>     
      <li class="nav-item">
        <a class="nav-link" href="<%=technicalsupports_path(:user_id=>nil)%>">
          <i class="fas fa-wrench"></i>
          <p>Teknik Destek Bakım Listesi</p>
        </a>
      </li> 
      <%if current_user.admin?%>
      <li class="nav-item">
        <a class="nav-link" href="<%=users_path%>">
          <i class="material-icons">group</i>
          <p>Kullanıcılar</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=customerbalances_path%>">
          <i class="material-icons">group</i>
          <p>Müşteri Bakiyeleri</p>
        </a>
      </li>
      <%end%>
      <%if signed_in?%>      
      <li class="nav-item ">
        <a class="nav-link" href="<%=logout_path%>"  data-method="delete">
          <i class="material-icons">power_settings_new</i>
          <p>Çıkış</p>
        </a>
      </li>
      <%end%>
    </ul>
  </div>
</div>