config/routes.rb
Rails.application.routes.draw do
  resources :technicalsupports do
    resources :tecnichsales 
  end
  resources :faultreqs
  resources :orders do
    resources :reqitems
  end
  resources :baskets do
    resources :salesproducts
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :customerbalances
  
  resources :products
  resources :brands
  get 'customer/index'
  get 'customer/new'
  get 'customer/show'
  get 'customer/edit'
  #sessions
  resource :session ,only: [:new, :create, :destroy]
  get '/oturum_ac', to: 'sessions#new', as: :login
  delete '/oturumu_kapat', to: 'sessions#destroy', as: :logout

  resources :users
  get '/kaydol', to: 'users#new',  as: :register
  get '/users/new', to: redirect('/kaydol')
  get '/:id', to: 'users#show', as: :profile
  get '/:id/edit', to: 'users#edit', as: :edit_profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sessions#new"
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
belongs_to :user
has_many :salesproducts
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
	validates :name, presence: true
	validates :name, :uniqueness => true
	before_save :uppercase_name
	def uppercase_name
		self.name.upcase!
	end
end

app/models/customerbalance.rb
class Customerbalance < ApplicationRecord
	belongs_to :user
end

app/models/faultreq.rb
class Faultreq < ApplicationRecord
belongs_to :user
has_one_attached :image
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :recipient, class_name: "User"
	belongs_to :actor, class_name: "User"
	belongs_to :notifiable, polymorphic: true

	scope :unread, ->{ where(:read_at=>nil) }
	scope :recent, ->{ order(created_at: :desc).limit(5) }
end

app/models/order.rb
class Order < ApplicationRecord
has_many :reqitems
belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :salesproducts
	has_many :reqitems
	has_many :tecnichsales
	belongs_to :brand
	validates :name, presence: true
	validates :amount, presence: true
	validates :unit_price, presence: true

end

app/models/reqitem.rb
class Reqitem < ApplicationRecord
	belongs_to :product
	belongs_to :order
end

app/models/salesproduct.rb
class Salesproduct < ApplicationRecord
belongs_to :product
belongs_to :user
belongs_to :basket
end

app/models/technicalsupport.rb
class Technicalsupport < ApplicationRecord
belongs_to :user
has_many :tecnichsales
end

app/models/tecnichsale.rb
class Tecnichsale < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :notifications, foreign_key: :recipient_id
	
	has_many :customerbalances
	has_many :orders
	has_many :salesproducts
	has_many :tecnichsales
	has_many :faultreqs
	has_many :baskets
	has_many :technicalsupports
	validates :username,   presence:   true,
	exclusion: {in: ['oturum_ac']},
	uniqueness: { case_sensitive: false },
	length:     { in: 4..12 },
	format:     { with: /\A[a-zA-Z][a-zA-Z0-9_-]*\Z/ },
	exclusion:  { in: ['oturum_ac'] }
	validates :first_name, presence:   true
	validates :last_name,  presence:   true
	validates :company_name, presence:   true
	validates :email,      presence:   true,
	uniqueness: { case_sensitive: false },
	email:      true

	def to_param
		username
	end
end

app/controllers/faultreqs_controller.rb
class FaultreqsController < ApplicationController
  before_action :set_faultreq, only: [:show, :edit, :update, :destroy]

  # GET /faultreqs
  # GET /faultreqs.json
  def index
    @faultreqs = Faultreq.all
  end

  # GET /faultreqs/1
  # GET /faultreqs/1.json
  def show
  end

  # GET /faultreqs/new
  def new
    @faultreq = Faultreq.new
  end

  # GET /faultreqs/1/edit
  def edit
  end

  # POST /faultreqs
  # POST /faultreqs.json
  def create
    o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
    string = (0...11).map { o[rand(o.length)] }.join
    @faultreq = Faultreq.new(faultreq_params)
    @faultreq.user=current_user
    @faultreq.key=string
    respond_to do |format|
      if @faultreq.save
        format.html { redirect_to @faultreq, notice: 'Faultreq was successfully created.' }
        format.json { render :show, status: :created, location: @faultreq }
      else
        format.html { render :new }
        format.json { render json: @faultreq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faultreqs/1
  # PATCH/PUT /faultreqs/1.json
  def update
    respond_to do |format|
      if @faultreq.update(faultreq_params)
        format.html { redirect_to @faultreq, notice: 'Faultreq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faultreq }
      else
        format.html { render :edit }
        format.json { render json: @faultreq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faultreqs/1
  # DELETE /faultreqs/1.json
  def destroy
    @faultreq.destroy
    respond_to do |format|
      format.html { redirect_to faultreqs_url, notice: 'Faultreq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faultreq
      @faultreq = Faultreq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faultreq_params
      params.require(:faultreq).permit(:description,:image,:key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/faultreqs_helper.rb
module FaultreqsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reqitems_helper.rb
module ReqitemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/faultreqs/_form.html.erb
   <div class="card">
    <div class="card-header card-header-primary">
      <img class="img pull-right" src="/assets/kep.png" style="width: 90px; height: 90px; padding-top: 20px;" />
      <h4 class="card-title" style="padding-top: 20px;">Arıza Bildirimi</h4>
      <p class="card-category">Arıza Bildiri Formu</p>
    </div>
    <div class="card-body">
      <%=form_for @faultreq, data: {abide: ''} do |form|%>
      <%if @faultreq.errors.any?%>
      <div class="row panel callout radius">
       <p>Aşağıdaki hataları düzeltip, tekrar deneyiniz.</p>
       <ul class="square">
         <%@faultreq.errors.full_messages.each do |message|%>
         <li><%=message%></li>
         <%end%>
       </ul>
     </div>
     <%end%>
     
     <div class="row">
      <div class="col-md-12">
       <div class="form-group">
        <label class="bmd-label-floating">Arıza Açıklaması</label>
        <%=form.text_field :description ,class: "form-control"%>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-12">
      <label class="bmd-label-floating">Arıza Yapan Ürünün Resmi</label> 
      <%=form.file_field :image%>
    </div>
  </div>

  


  <button type="submit" class="btn btn-primary btn-block ">Arızayı Bildir</button>
  <%end%>
</div>
</div>

app/views/faultreqs/edit.html.erb
<h1>Editing Faultreq</h1>

<%= render 'form', faultreq: @faultreq %>

<%= link_to 'Show', @faultreq %> |
<%= link_to 'Back', faultreqs_path %>

app/views/faultreqs/index.html.erb
 <div class="wrapper ">
  <%= render 'shared/sidebar'%>
  <div class="main-panel">
    <%= render 'shared/navbar'%>
    <div class="content">

      <div class="container-fluid">

        <br>
        <div class="row">
          <div class="col-md-3"><!--left col-->

            <div class="text-center">
              <img src="/assets/kep.png" style="width: 250px; height: 200px;" class="avatar img-circle img-thumbnail" alt="avatar">
            </div>
            <hr> 
            <h3 class="text-center"><%=current_user.first_name%>  <%=current_user.last_name%></h3>
            <hr>
            <%= form_with(model: Order.new, local: true) do |form| %>

            <div class="field">
              <%= form.hidden_field :req_key %>
            </div>

            <div class="actions">
              <%= form.submit 'Sipariş Oluştur',class: "btn btn-primary btn-round btn-block" %>
            </div>
            <% end %> 
          </div><!--/col-3-->


          <div class="col-md-9">

            <div class="card">
              <div class="card-header card-header-primary">

                <div class="row">
                  <div class="col-md-6">
                    <h4 class="card-title ">Siparisler</h4>
                    <p class="card-category">Siparis Listesi</p>
                  </div>
                  <div class="col-md-6">

                    <form class="navbar-form">
                      <div class="input-group no-border">
                        <input type="text" id="search" onkeyup="myFunction()" value="" class="form-control" placeholder="Kullanıcı İsiminde Arayınız." style="color: white;">
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                          <i class="material-icons">search</i>
                          <div class="ripple-container"></div>
                        </button>
                      </div>
                    </form>  

                  </div>
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive">

                  <table class="table" id="myTable">
                    <thead>
                      <tr>
                        <th>ARIZA ID</th>
                        <th>ARIZA KODU</th>
                        <th>ARIZA BİLDİREN ŞİRKET</th>
                        <th>TARİH</th>
                        <th>SEÇENEKLER</th>
                      </tr>
                    </thead>
                    <tbody class="items">
                      <% @faultreqs.each do |fault| %>
                      <tr>
                        <td><%=fault.id%></td>
                        <td><%=link_to fault.key,faultreq_path(fault)%></td>
                        <td><%=fault.user.company_name%></td>
                        <td><%=fault.created_at.strftime('%d-%m-%Y')%></td>
                        <td><%= link_to '', fault, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-warning fa fa-trash" %><%=link_to '',faultreq_path(fault),class: "btn btn-warning fa fa-eye"%></td>
                      </tr>
                      <%end%>
                    </tbody>
                  </table>

                </div>

              </div>

            </div>

          </div>

        </div>
      </div>

    </div>
    <%= render 'shared/footer'%>
  </div>
</div>

<script>  
  $(document).ready(function(){  
    $('#search').keyup(function(){  
      search_table($(this).val());  
    });  
    function search_table(value){  
      $('#myTable tr').each(function(){  
        var found = 'false';  
        $(this).each(function(){  
          if($(this).text().toUpperCase().indexOf(value.toUpperCase()) >= 0)  
          {  
            found = 'true';  
          }  
        });  
        if(found == 'true')  
        {  
          $(this).show();  
        }  
        else  
        {  
          $(this).hide();  
        }  
      });  
    }  
  });  
</script>  

app/views/faultreqs/new.html.erb
 <div class="wrapper ">
 	<%= render 'shared/sidebar'%>
 	<div class="main-panel">
 		<%= render 'shared/navbar'%>
 		<div class="content">

 			<div class="container-fluid">

 				<br>
 				<div class="row">
 					<div class="col-md-3"><!--left col-->

 						<div class="text-center">
 							<img src="/assets/kep.png" style="width: 250px; height: 200px;" class="avatar img-circle img-thumbnail" alt="avatar">
 						</div>
 						<hr> 
 						<h3 class="text-center"><%=current_user.first_name%>  <%=current_user.last_name%></h3>
 						<hr>
 						<%= form_with(model: Order.new, local: true) do |form| %>

 						<div class="field">

 							<%= form.hidden_field :req_key %>
 						</div>

 						<div class="actions">
 							<%= form.submit 'Sipariş Oluştur',class: "btn btn-primary btn-round btn-block" %>
 						</div>
 						<% end %>
 						<hr>						
 						<% if current_user==@user%>
 						<%=link_to "Hesabı Düzenle", edit_user_path(@user), class: "btn btn-primary btn-round btn-block"%>

 						<%= button_to "Hesabı sil", @user, method: :delete, data:{confirm: 'Hesabı silmek istediğinize emin misiniz?'}, class: "btn btn-primary btn-round btn-block" %></p>
 						<%end%>
 						<br>
 					</div><!--/col-3-->


 					<div class="col-md-9">
 						<%= render 'form', faultreq: @faultreq %>

 					</div>

 				</div>
 			</div>

 		</div>
 		<%= render 'shared/footer'%>
 	</div>
 </div>
 
 <script>  
 	$(document).ready(function(){  
 		$('#search').keyup(function(){  
 			search_table($(this).val());  
 		});  
 		function search_table(value){  
 			$('#myTable tr').each(function(){  
 				var found = 'false';  
 				$(this).each(function(){  
 					if($(this).text().toUpperCase().indexOf(value.toUpperCase()) >= 0)  
 					{  
 						found = 'true';  
 					}  
 				});  
 				if(found == 'true')  
 				{  
 					$(this).show();  
 				}  
 				else  
 				{  
 					$(this).hide();  
 				}  
 			});  
 		}  
 	});  
 </script>  

app/views/faultreqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @faultreq.description %>
</p>

<%= link_to 'Edit', edit_faultreq_path(@faultreq) %> |
<%= link_to 'Back', faultreqs_path %>