config/routes.rb
Rails.application.routes.draw do
  resources :technicalsupports do
    resources :tecnichsales 
  end
  resources :faultreqs
  resources :orders do
    resources :reqitems
  end
  resources :baskets do
    resources :salesproducts
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :customerbalances
  
  resources :products
  resources :brands
  get 'customer/index'
  get 'customer/new'
  get 'customer/show'
  get 'customer/edit'
  #sessions
  resource :session ,only: [:new, :create, :destroy]
  get '/oturum_ac', to: 'sessions#new', as: :login
  delete '/oturumu_kapat', to: 'sessions#destroy', as: :logout

  resources :users
  get '/kaydol', to: 'users#new',  as: :register
  get '/users/new', to: redirect('/kaydol')
  get '/:id', to: 'users#show', as: :profile
  get '/:id/edit', to: 'users#edit', as: :edit_profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sessions#new"
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
belongs_to :user
has_many :salesproducts
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
	validates :name, presence: true
	validates :name, :uniqueness => true
	before_save :uppercase_name
	def uppercase_name
		self.name.upcase!
	end
end

app/models/customerbalance.rb
class Customerbalance < ApplicationRecord
	belongs_to :user
end

app/models/faultreq.rb
class Faultreq < ApplicationRecord
belongs_to :user
has_one_attached :image
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :recipient, class_name: "User"
	belongs_to :actor, class_name: "User"
	belongs_to :notifiable, polymorphic: true

	scope :unread, ->{ where(:read_at=>nil) }
	scope :recent, ->{ order(created_at: :desc).limit(5) }
end

app/models/order.rb
class Order < ApplicationRecord
has_many :reqitems
belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :salesproducts
	has_many :reqitems
	has_many :tecnichsales
	belongs_to :brand
	validates :name, presence: true
	validates :amount, presence: true
	validates :unit_price, presence: true

end

app/models/reqitem.rb
class Reqitem < ApplicationRecord
	belongs_to :product
	belongs_to :order
end

app/models/salesproduct.rb
class Salesproduct < ApplicationRecord
belongs_to :product
belongs_to :user
belongs_to :basket
end

app/models/technicalsupport.rb
class Technicalsupport < ApplicationRecord
belongs_to :user
has_many :tecnichsales
end

app/models/tecnichsale.rb
class Tecnichsale < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :notifications, foreign_key: :recipient_id
	
	has_many :customerbalances
	has_many :orders
	has_many :salesproducts
	has_many :tecnichsales
	has_many :faultreqs
	has_many :baskets
	has_many :technicalsupports
	validates :username,   presence:   true,
	exclusion: {in: ['oturum_ac']},
	uniqueness: { case_sensitive: false },
	length:     { in: 4..12 },
	format:     { with: /\A[a-zA-Z][a-zA-Z0-9_-]*\Z/ },
	exclusion:  { in: ['oturum_ac'] }
	validates :first_name, presence:   true
	validates :last_name,  presence:   true
	validates :company_name, presence:   true
	validates :email,      presence:   true,
	uniqueness: { case_sensitive: false },
	email:      true

	def to_param
		username
	end
end

app/controllers/technicalsupports_controller.rb
class TechnicalsupportsController < ApplicationController
  before_action :admin_check, only: [:edit,:update,:destroy,:new,:create]
  before_action :set_technicalsupport, only: [:show, :edit, :update, :destroy]


  def index
   if params[:user_id]==nil
    @user=current_user
    @technicalsupports=Technicalsupport.all.order("created_at DESC")
  else    
    @technicalsupports = Technicalsupport.where(user_id: params[:user_id]).order("created_at DESC")
    @user=User.find(params[:user_id])
  end
end


def show
end

def new

  @technicalsupport = Technicalsupport.new
  @user=User.find(params[:u_id])
end

def edit
end


def create
 o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
 string = (0...11).map { o[rand(o.length)] }.join
 @technicalsupport = Technicalsupport.new(technicalsupport_params)

 @technicalsupport.key=string


 respond_to do |format|
  if @technicalsupport.save

    if Customerbalance.exists?(user_id: @technicalsupport.user_id)
      @customerbalance=Customerbalance.find_by_user_id(@technicalsupport.user_id)

      @customerbalance.user_id=@technicalsupport.user_id
      @customerbalance.total_balance+=@technicalsupport.workmanship_price
      @customerbalance.save
    else
      @customerbalance=Customerbalance.new(:user_id=>@technicalsupport.user_id,:total_balance=> @technicalsupport.workmanship_price)
      @customerbalance.save
    end
    format.html { redirect_to @technicalsupport, notice: 'Technicalsupport was successfully created.' }
    format.json { render :show, status: :created, location: @technicalsupport }
  else
    format.html { render :new }
    format.json { render json: @technicalsupport.errors, status: :unprocessable_entity }
  end
end
end


def update

 @customerbalance=Customerbalance.find_by_user_id(@technicalsupport.user_id)
 @customerbalance.total_balance-=@technicalsupport.workmanship_price
 @customerbalance.save
 respond_to do |format|
  if @technicalsupport.update(technicalsupport_params)
   @customerbalance.total_balance+=@technicalsupport.workmanship_price
   @customerbalance.save
   format.html { redirect_to @technicalsupport, notice: 'Technicalsupport was successfully updated.' }
   format.json { render :show, status: :ok, location: @technicalsupport }
 else
  format.html { render :edit }
  format.json { render json: @technicalsupport.errors, status: :unprocessable_entity }
end
end
end

def destroy
  @technicalsupport.destroy
  respond_to do |format|
    format.html { redirect_to technicalsupports_url, notice: 'Technicalsupport was successfully destroyed.' }
    format.json { head :no_content }
  end
end

private
def set_technicalsupport
  @technicalsupport = Technicalsupport.find(params[:id])
end

def technicalsupport_params
  params.require(:technicalsupport).permit(:workmanship_price, :total_price, :description,:key,:user_id)
end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/faultreqs_helper.rb
module FaultreqsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reqitems_helper.rb
module ReqitemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/technicalsupports_helper.rb
module TechnicalsupportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/technicalsupports/_form.html.erb
  <div class="card">
    <div class="card-header card-header-primary">
      <img class="img pull-right" src="/assets/kep.png" style="width: 90px; height: 90px; padding-top: 20px;" />
      <h4 class="card-title" style="padding-top: 20px;">Kayıt</h4>
      <p class="card-category">Otomasyon Kayıt</p>
    </div>
    <div class="card-body">
      <%=form_for @technicalsupport, data: {abide: ''} do |form|%>
      <%if @technicalsupport.errors.any?%>
      <div class="row panel callout radius">
        <p>Aşağıdaki hataları düzeltip, tekrar deneyiniz.</p>
        <ul class="square">
          <%@technicalsupport.errors.full_messages.each do |message|%>
          <li><%=message%></li>
          <%end%>
        </ul>
      </div>
      <%end%>
      <% if technicalsupport.user_id.blank? %>
      <% uid = params[:user_id] %>
      <% else %>
      <% uid = technicalsupport.user_id  %>
      <% end %>

      <%=form.hidden_field :user_id,:value=>params[:u_id]%>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label class="bmd-label-floating">Teknik Bakım Açıklaması</label>
            <%=form.text_area :description, class: "form-control"%>
          </div>
        </div>
      </div>


      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label class="bmd-label-floating">İşçilik Ücreti</label>
            <%=form.number_field :workmanship_price, class: "form-control"%>
          </div>
        </div>
      </div>      

      <div class="row">
        <div class="col-md-6">
          <%= link_to 'Geri', :back, class: "btn btn-primary btn-block" %>
        </div>
        <div class="col-md-6"><button type="submit" class="btn btn-primary btn-block ">Kaydet</button>
        </div>
      </div>
      <%end%>
    </div>
  </div>

app/views/technicalsupports/edit.html.erb
 <div class="wrapper ">
 	<%= render 'shared/sidebar'%>
 	<div class="main-panel">
 		<%= render 'shared/navbar'%>
 		<div class="content">

 			<div class="container-fluid">

 				<br>
 				<div class="row">
 					<div class="col-md-3"><!--left col-->

 						<div class="text-center">
 							<img src="/assets/kep.png" style="width: 250px; height: 200px;" class="avatar img-circle img-thumbnail" alt="avatar">
 						</div>
 						<hr> 
 						<h3 class="text-center"><%=current_user.first_name%>  <%=current_user.last_name%></h3>
 						<hr>

 						<%=link_to 'New Technicalsupport Form', new_technicalsupport_path,class: "btn btn-primary btn-round btn-block"%>
 						<%= form_with(model: Order.new, local: true) do |form| %>

 						<div class="field">

 							<%= form.hidden_field :req_key %>
 						</div>

 						<div class="actions">
 							<%= form.submit 'Sipariş Oluştur',class: "btn btn-primary btn-round btn-block" %>
 						</div>
 						<% end %>	
 						<%= form_with(model: Basket.new, local: true) do |form| %>

 						<div class="field">

 							<%= form.hidden_field :key %>
 						</div>

 						<div class="actions">
 							<%= form.submit 'Satış Oluştur',class: "btn btn-primary btn-round btn-block" %>
 						</div>
 						<% end %>
 						<hr>					
 						<% if current_user==@user%>
 						<%=link_to "Hesabı Düzenle", edit_user_path(@user), class: "btn btn-primary btn-round btn-block"%>

 						<%= button_to "Hesabı sil", @user, method: :delete, data:{confirm: 'Hesabı silmek istediğinize emin misiniz?'}, class: "btn btn-primary btn-round btn-block" %></p>
 						<%end%>
 						<br>
 					</div><!--/col-3-->


 					<div class="col-md-9">
 						<%= render 'form', technicalsupport: @technicalsupport %>


 					</div>

 				</div>
 			</div>

 		</div>
 		<%= render 'shared/footer'%>
 	</div>
 </div>

 <script>  
 	$(document).ready(function(){  
 		$('#search').keyup(function(){  
 			search_table($(this).val());  
 		});  
 		function search_table(value){  
 			$('#myTable tr').each(function(){  
 				var found = 'false';  
 				$(this).each(function(){  
 					if($(this).text().toUpperCase().indexOf(value.toUpperCase()) >= 0)  
 					{  
 						found = 'true';  
 					}  
 				});  
 				if(found == 'true')  
 				{  
 					$(this).show();  
 				}  
 				else  
 				{  
 					$(this).hide();  
 				}  
 			});  
 		}  
 	});  
 </script>  

app/views/technicalsupports/index.html.erb
 <div class="wrapper ">
  <%= render 'shared/sidebar'%>
  <div class="main-panel">
    <%= render 'shared/navbar'%>
    <div class="content">

      <div class="container-fluid">

        <br>
        <div class="row">
          <div class="col-md-3"><!--left col-->

            <div class="text-center">
              <img src="/assets/kep.png" style="width: 250px; height: 200px;" class="avatar img-circle img-thumbnail" alt="avatar">
            </div>
            <hr> 
            <h3 class="text-center"><%=@user.first_name%>  <%=@user.last_name%></h3>
            <hr>
            
            
            <%= form_with(model: Order.new, local: true) do |form| %>

            <div class="field">
              <%= form.hidden_field :req_key %>
            </div>

            <div class="actions">
              <%= form.submit 'Sipariş Oluştur',class: "btn btn-primary btn-round btn-block" %>
            </div>
            <% end %> 
            
          </div><!--/col-3-->
          <div class="col-md-9">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">

                 <div class="row">
                  <div class="col-md-6">
                    <h4 class="card-title ">Teknik Destek</h4>
                    <p class="card-category">Teknik Destek Özeti</p>
                  </div>
                  <div class="col-md-6">

                    <form class="navbar-form">
                      <div class="input-group no-border">
                        <input type="text" id="search" onkeyup="myFunction()" value="" class="form-control" placeholder="Kullanıcı İsiminde Arayınız." style="color: white;">
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                          <i class="material-icons">search</i>
                          <div class="ripple-container"></div>
                        </button>
                      </div>
                    </form>  

                  </div>
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive">

                 <table class="table" id="myTable">
                  <thead>
                    <tr>
                     <th>Support ID</th>
                     <th>USER ID</th>
                     <th>DATE</th>
                     <th>PRODUCT COUNT</th>
                     <th>TOTAL PRICE</th>
                   </tr>
                 </thead>
                 <tbody class="items">
                  <% @technicalsupports.each do |support| %>
                  <tr>
                    <td><%=link_to support.key,technicalsupport_tecnichsales_path(support)%></td>
                    <td><%=support.user_id%></td>
                    <td><%=support.created_at.strftime('%d-%m-%Y')%></td>
                    <td><%=support.tecnichsales.count%></td>
                    <td><%=support.tecnichsales.sum(:total_price)+support.workmanship_price%></td>
                    <td><%= link_to 'Sil', support, method: :delete, data: { confirm: 'Are you sure?' } %> <%= link_to 'Düzenle', edit_technicalsupport_path(support) %></td> 
                  </tr>
                  <%end%>
                </tbody>
              </table>

            </div>

          </div>

        </div>
      </div>
    </div>

  </div>
</div>

</div>
<%= render 'shared/footer'%>
</div>
</div>

<script>  
  $(document).ready(function(){  
   $('#search').keyup(function(){  
    search_table($(this).val());  
  });  
   function search_table(value){  
    $('#myTable tr').each(function(){  
     var found = 'false';  
     $(this).each(function(){  
      if($(this).text().toUpperCase().indexOf(value.toUpperCase()) >= 0)  
      {  
       found = 'true';  
     }  
   });  
     if(found == 'true')  
     {  
      $(this).show();  
    }  
    else  
    {  
      $(this).hide();  
    }  
  });  
  }  
});  
</script>  

app/views/technicalsupports/new.html.erb
 <div class="wrapper ">
 	<%= render 'shared/sidebar'%>
 	<div class="main-panel">
 		<%= render 'shared/navbar'%>
 		<div class="content">

 			<div class="container-fluid">

 				<br>
 				<div class="row">
 					<div class="col-md-3"><!--left col-->

 						<div class="text-center">
 							<img src="/assets/kep.png" style="width: 250px; height: 200px;" class="avatar img-circle img-thumbnail" alt="avatar">
 						</div>
 						<hr> 
 						<h3 class="text-center"><%=@user.first_name%>  <%=@user.last_name%></h3>
 						<hr>

 						<%=link_to 'New Technicalsupport Form', new_technicalsupport_path,class: "btn btn-primary btn-round btn-block"%>
 						<%= form_with(model: Order.new, local: true) do |form| %>

 						<div class="field">

 							<%= form.hidden_field :req_key %>
 						</div>

 						<div class="actions">
 							<%= form.submit 'Sipariş Oluştur',class: "btn btn-primary btn-round btn-block" %>
 						</div>
 						<% end %>	
 						<%= form_with(model: Basket.new, local: true) do |form| %>

 						<div class="field">

 							<%= form.hidden_field :key %>
 						</div>

 						<div class="actions">
 							<%= form.submit 'Satış Oluştur',class: "btn btn-primary btn-round btn-block" %>
 						</div>
 						<% end %>
 						<hr>					
 						<br>
 					</div><!--/col-3-->


 					<div class="col-md-9">
 						<%= render 'form', technicalsupport: @technicalsupport %>


 					</div>

 				</div>
 			</div>

 		</div>
 		<%= render 'shared/footer'%>
 	</div>
 </div>

 <script>  
 	$(document).ready(function(){  
 		$('#search').keyup(function(){  
 			search_table($(this).val());  
 		});  
 		function search_table(value){  
 			$('#myTable tr').each(function(){  
 				var found = 'false';  
 				$(this).each(function(){  
 					if($(this).text().toUpperCase().indexOf(value.toUpperCase()) >= 0)  
 					{  
 						found = 'true';  
 					}  
 				});  
 				if(found == 'true')  
 				{  
 					$(this).show();  
 				}  
 				else  
 				{  
 					$(this).hide();  
 				}  
 			});  
 		}  
 	});  
 </script>  

app/views/technicalsupports/show.html.erb
<div class="wrapper ">
	<%= render 'shared/sidebar'%>
	<div class="main-panel">
		<%= render 'shared/navbar'%>
		<div class="content">

			<div class="container-fluid">

				<div class="col-md-12">
					<%= render 'tecnichsales/form', tecnichsale: @tecnichsale %>
					<div class="card">
						<div class="card-header card-header-primary">

							<div class="row">
								<div class="col-md-6">
									<h4 class="card-title ">Teknik Destek</h4>
									<p class="card-category">Teknik Destek Kodu: <%=@technicalsupport.key%></p>
								</div>
								<div class="col-md-6">
									<form class="navbar-form">
										<div class="input-group no-border">
											<input type="text" id="search" onkeyup="myFunction()" value="" class="form-control" placeholder="Kullanıcı İsiminde Arayınız." style="text-color: white;">
											<button type="submit" class="btn btn-white btn-round btn-just-icon">
												<i class="material-icons">search</i>
												<div class="ripple-container"></div>
											</button>
										</div>
									</form>  
								</div>
							</div>
						</div>
						<div class="all_data">
							<%=render 'tecnichsales/item'%>
						</div>

					</div>
				</div>
				<%= render 'shared/footer'%>
			</div>
		</div>
	</div>

	<script>  
		$(document).ready(function(){  
			$('#search').keyup(function(){  
				search_table($(this).val());  
			});  
			function search_table(value){  
				$('#myTable tr').each(function(){  
					var found = 'false';  
					$(this).each(function(){  
						if($(this).text().toUpperCase().indexOf(value.toUpperCase()) >= 0)  
						{  
							found = 'true';  
						}  
					});  
					if(found == 'true')  
					{  
						$(this).show();  
					}  
					else  
					{  
						$(this).hide();  
					}  
				});  
			}  
		});  
	</script>  